name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH
      env:
        KEY: ${{ secrets.KEY }}
      run: |
        mkdir ~/.ssh
        echo "$KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Run SSH commands
      run: |
        ssh -o StrictHostKeyChecking=no pi@home.ysshah.dev "
          cd /home/pi/rasapper
          git fetch
          git reset --hard origin/main
          npm install
          npm run build
          pm2 restart rasapper
          "
